[package]
name = "raft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
replicate = {path = "../replicate" }
replicate-macro = { path = "../replicate-macro" }