[package]
name = "raft-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
syn = {version = "1.0.52", features = ["full", "extra-traits"]}
prost = "0.11"